let js = "amazing";
console.log("programing is very cool");
console.log(js);

// let firstName = "Sourabh singh";
// let Sourabh;
// console.log(firstName);
// //boolean value code here

//let myName = "Manishsingh";
//console.log("myName");
let sourabh = true;
console.log(sourabh);
console.log(typeof true);
console.log(typeof "manishsingh");
console.log(typeof 09);

// sourabh = 'coder';
// console.log(typeof "sourabh");*/

// /*const manju = 2022
// const ageSurbhi = manju - 2000;
// const ageSourabh = manju - 1997;
// console.log(ageSurbhi *2,ageSourabh/2);

//averarge age calculate for basic formulas
const jivan = 50;
const manju = 45;
const surbhi = 22;
//print average age and indivisual how many years below with his father
const belowage = function (manju, surbhi) {
  return jivan - manju;
  return jivan - surbhi;
};
console.log(belowage(manju), belowage(surbhi));

const Name = "Sourabh";
const surName = "Singh";
console.log(Name + " " + surName);

let x = 12 + 5 * 2;
let y = 12 + 5;
x += 7;
y++;
console.log(x, y);

// const ageSourabh = 2022 - 1997,
// console.log(ageSurbhi, ageSourabh)

let markWeight = 78;
let markheight = 1.69;
let joneWeight = 92;
let joneheight = 1.88;

let markBmi = markWeight / markheight ** 2;
let joneBmi = joneWeight / joneheight ** 2;
console.log(markBmi, joneBmi);

console.log(markBmi > joneBmi);
console.log(markWeight, markheight);
console.log(joneWeight, joneheight);
let averageWeight = (joneWeight + markWeight) / 2;
console.log(markWeight, joneWeight, averageWeight);

const name = "sourabh";
const year = 2022;
const job = "Accountant";
const birthyear = 1997;
const address = "Currently iam stay in limbodi indore my profession is ";

console.log(
  "i'm" +
    " " +
    name +
    " " +
    (year - birthyear) +
    " " +
    "year" +
    " " +
    " " +
    "old" +
    " " +
    address +
    job
);
// //add strings in code
console.log(`i'm ${name} ${year - birthyear} year old ${address}${job}`);

// /*how to divide strings in multiple lines
const companyName = "Rackbank Data centers pvt. ltd.";
const gstNumber = "23AACBGDHGDKL";
const companyAddress = "1st floor crystal it park";
const estabalisment = 1990;
const currentYear = 2022;

console.log(`my company name ${companyName}
in establish in ${currentYear - estabalisment} year ago,
this is our company gst number ${gstNumber}
is located in ${companyAddress}`);

// /*const age;
// if(age >= 18) {
//         console.log(`you are eligible for appearing ssc exams`)
// }else{
//     console.log(`you are not eligible for ssc exams`)
// }

// /*const button = 7
// if(button >= 10){
//     let button = "Switch Turn On"
// }else{
//     let button = "Switch Turn Off"*/

// /*const age = 17;
// let person;
// if(age >= 18){
//     person = "You are eligible"
// }else {
//     person = "You are not eligible"
// }
// console.log(person);

// let markWeight = 78;
// let markheight = 1.69;
// let joneWeight = 92;
// let joneheight = 1.88;*/
// //let markbmi = markWeight/joneheight**2;
// //let jonebmi = joneWeight/joneheight**2;
// /*let markbmi = 29;
// let jonbmi = 28.6;
// let marks;

// if(markbmi>=28.6){
//     marks = "marks bmi higher than jones"
// }else{
//     marks = "marks bmi lower than jones"
// }
// console.log (marks)*/
// //number funtion how to change string to number and add number

// /*const inputQauntity = "200";

// console.log(Number (inputQauntity),  inputQauntity)

// console.log(Number(inputQauntity)+20,inputQauntity)
// console.log(String(60),6000)

// console.log('10'- 5- 6 * 2 +'5')
// console.log('70'+ 60 - 6);
// const n = 5;
// console.log(n + 1 - '5')
// const nh = "6"
// console.log(nh + 10 - 5);
// //Boolean values change into if else funtion
// console.log(Boolean(0))
// console.log(Boolean(""))
// console.log(Boolean('sourabh'))
// console.log(Boolean(500))
// console.log(Boolean({}))
// console.log(Boolean('300'))
// const quantity = 0
// //ud else funtion how it is work
// if(quantity){ //if else function
//     console.log("you enough some quantity")
// }else{
//     console.log("you have purchae some quantity")
// }

// let weight = 1 //how to work boolean type data change weight
// if(weight){
//     console.log('you reduce your weight for daily excersize')
// }else{
//     console.log('you need to some extra nutriton')

// }*/

// const favourite = Number(prompt("what is your favourite number"));

// if (favourite === 23) {
//   console.log("23 is the amazing number");
// } else if (favourite === 50) {
//   console.log("50 is the good number");
// } else if (favourite === 100) {
//   console.log("100 is the good number");
// } else console.log("mismatch with input data");

// const age = 18;
// if(age >= 18) {
//         console.log(`you are eligible for appearing ssc exams`)
//         console.log(typeof age)
// }ifelse(age >= 20) {console.log(`this is the if else`)
// } else (console.log(`you are not eligible for ssc exams`))

// }
// //how to provide input value and program run according to our instraction
//  /*let sourabh = Number(prompt("Type Your Number Here"));
//  console.log(sourabh);
//  console.log(typeof sourabh);
//  if(sourabh === 18){
//     console.log("18 year old")
//   } else if(sourabh===30){
//    console.log("30 is the good age to job prefession")
// }else{(sourabh = 70);console.log("18 and 30 is the good number")
// }*/

// /*let surbhi = Number(prompt("type surbhi subject marks"));
// if(surbhi===50){console.log("maths")
//     console.log(typeof surbhi)
//   }else if(surbhi===70) {console.log("English")
// }else if(surbhi===90) {console.log("Science")
// }else{
//     console.log("Other subject")
// }*/
// //this is if and else function
// /*let manish = Number(prompt( "type number here"))
// if(manish===600){
//     console.log("selected in railway exams")
//     console.log(typeof manish);
// }else if (manish === 300){
//     console.log("manish should more prepare for railway exams")
// }else if(manish === 100){
//     console.log("manish had going to home now")
// }else{
//    console.log("wrogn number")
// 100}
// if(manish !==60){
//     console.log("this is the correct value")
// }*/
// //this is the boolean logical opratorts "and(&&), or(||) , not(!)"
const havelaptop = false;
const havewatch = true;
const havebag = false;

if (havelaptop || (havewatch && havebag)) {
  console.log("you have a laptop and watch or bag");
} else {
  console.log("you have a don't need all three items");
}
if (havelaptop || havewatch || !havebag) {
  console.log(
    "this is the or orator when on variable be true so all variable is true"
  );
}
if (havebag && havewatch && havebag) {
  console.log(
    "this is the and oprator work is true when one variable is false all funtion is false"
  );
}
if ((havelaptop && havewatch) || havebag) {
  console.log("this if statement show the not oprator");
}
// /*
// const ilearncoding = false;
// const preparecompetative = true;
// const runningpg = true;
// if(ilearncoding||preparecompetative||runningpg){
//     console.log("this is the great work")
// }else{
//     console.log("don't forget to any day in learning")
// }
// */
// /*const dolphins = 96 + 108 + 89;
// const koalas = 88 + 91 + 110;
// const averageofdolphins = dolphins/3;
// const averageofkoalas = koalas/3;
// console.log(dolphins,koalas,averageofdolphins,averageofkoalas)
// if(averageofdolphins>averageofkoalas){
//     console.log("winner is dolphins")
// }else if(averageofdolphins<averageofkoalas)
//     console.log("winner is koalas")
// else if (averageofdolphins===averageofkoalas){
//     console.log("both are winner")
// }*/
// // challage 3 logical oprator
// /*const dolphins = 97 + 112 + 101;
// const koalas = 109 + 95 + 106;
// const scoredolphins = dolphins/3;
// const scorekoalas = koalas/3;
// console.log(scorekoalas,scoredolphins)

// if(scorekoalas>scoredolphins&&scorekoalas>=100){
//     console.log("koalas win the trophy")
// }else if(scoredolphins>scorekoalas&&scoredolphins>=100){
//     console.log("dolphins win the trophy")
// }else if(scoredolphins===scorekoalas){
//     console.log("both are winner")
// }*/
const company = "Quality Controler";

switch (company) {
  case "hr manager":
    console.log("hr manage to all company employees");
    break;
  case "accountant":
    console.log("accountand manage company finnace affaires");
    break;
  case "sales":
    console.log("sales team create all the sales stratgies");
    break;
  case "network engineer":
    console.log("handle company area network");
    break;
  case "Quality Controler":
    console.log("check all the company product quality");
    break;
  case "production manager":
    console.log("Handle all the PRODUCTION RELATED QUREIES");
    break;
  default:
    console.log("this is the not company part");
}

// //statement and expression concept (the condition ternary oprator)
// const age = 27;
// const sourabh = age >= 45 ? 'water' : 'wine' //this is the if and else function
// console.log(sourabh);

const bday = 2022 - 25;
const netbday = bday;
const sour =
  netbday < 2000
    ? `your born in ninties your birth year is ${bday}`
    : `you born in tewnties your birth year is ${bday}`;
console.log(sour);

// //  if and else function
// //  const birthyear = 19 //birthday variable
// // if(birthyear=== "1997"){  // if condition
// //     console.log("sourabh")
// //     }else if (birthyear ==1998){ //else if condition
// //         console.log('shubham')
// //     }else{
// //         console.log('no one'); // else condition
// //     }
// console.log(`i am name is ${}my birthyear is 1997`)

// // const age = 55;
// // const sourabh = age >= 45 ? 'water' : 'wine'//this is the if and else function
// // console.log(sourabh);
// // // console.log(`i want to ${age >= 45 ? 'water' : 'wine'}`)

// // // challenge 04
// const invoice = 350;
// const tip = invoice>=50 && invoice<=300 ? invoice * .15 : invoice * .20;
// console.log(`invoice amount ${invoice} tip amount ${tip} total amount${invoice + tip}`);

// // if else advance version
// const rate = 5000;
// const fan = rate<=5000 ? 'purchase this item' : 'not purchase this item'
// console.log(fan);
// console.log(`if your fan price ${rate} purchase this item`)

//learn fuction how to work in coding******
// function multi(){//this is the name of function and (this is the argument)
//    console.log("this is the my first code in fuction");
// }
// multi();
// multi();
// multi();

// function nameoflaptop (dell, hp){ //this is the function name argument always put in strings
//     if(dell >= 50000){ // add if else condition
//         console.log('this is the saleable items')
//     }else
//     console.log(`this is the not a saleable items`)
//     const laptop = ` dell lapto price is ${dell} and hp laptop price is ${hp}`
//     return laptop; // what we want to return in funtion like 335 line

// }
// let laptopprice = nameoflaptop(100000, 10000); // define what i return value in this argument
// console.log(laptopprice)

// function companysalary(divyaraj,radhe ){
//     const salary1 = (`divyaraj salary is ${divyaraj}`);
//     const salary2 = (`radhe salary is ${radhe}`);
//     const totalsalary = (`total salary is ${divyaraj + radhe}`);
//     return totalsalary,salary1,salary2;
//     }
//     const totalsalary = companysalary(70000,120000,)
//     console.log(totalsalary)

// function check(a,b){
//     const check1 = `check 01`
//      return check1
// }
// function check(a,b,c){
//     const check2 = `check 02`
//     return check2
// }
// function check(a){
//     const check3 = `check 03`
//     return check3
// }
// function check(b){
//     const check4 = "check 04"
//     return check4
// }
// const total = check('sssssss',"gfasg","fsdas")
// console.log(total);

// //create function for i have 2 diffrent brand laptop how to show in console with fuction
// function laptoP(dell,hp,lenovo){
//     const wehave = (`we have DELL laptop price ${dell}`);
//    const ihave = (` HP price is ${hp}`);
//    const somehave = (`lenovo laptop price is ${lenovo}`);
//     return (wehave,ihave,somehave)
// }
// const wehave = laptoP(50000,100000,500123);
// console.log(wehave)

// const room = "tabl"
// switch (room){
// case "fan" :
// console.log(`we have one fan of bajaj company`)
// break
// case 'table':
//     console.log("we have one table of red colour")
// case "mobile" :
//     console.log(`we have one of my mobile of realme company`)
//     break
// case "charger" :
//     console.log(`we have two charger for two diffrent mobiles`)
//     break
// case "laptop" :
//     console.log(`we have a laptop for coding pratices`)
//     break
// default :
// console.log(`this is not availble in room at this time`);
// }

// // const calcage1= function (year){
// //     return  1997 - year
// // }
// // const sourabhage = calcage1(2022);
// // console.log(sourabhage);

// // const totalprice = function(intrest){
// // return 500 + intrest
// // }
// // const priceintrest = totalprice(2000);
// // console.log(priceintrest);

// //funtion in fuction how to it is work
// // function brands(phones){
// //     return phones * 6
// // }
// // function mobiles(redmi,samsung){
// //     const mobile1 = brands(redmi);
// //     const mobile2 = brands(samsung);
// //     const bothmobile = `i have ${mobile1} redmi brands phones & ${mobile2} samsung phones`
// //     return bothmobile;
// // }
// // console.log(mobiles(4,5))
// //function calling another function
// // function copies(pages){
// //     return pages * 10
// // }
// // function bookes(speedy,arthmetic){
// // const book1 = copies(speedy)
// // const book2 = copies(arthmetic)
// // const view = (`we will purchase ${book1} speedy books & we also purchase ${book2} arthmetic books`)
// // return view
// // }
// // const noofbookes =  bookes(4,6)
// // console.log(noofbookes)

// const calcage1 = function (birthyear){
//     return 2022 - birthyear;
// }
// const age = calcage1(1997)
// console.log(age);

// const calcage2 = birthyear => 2022- birthyear; //calcage2 is function //birthyear function parameter // 2022-birthyear is retrn value
// const age2 = calcage2(1997) //function calling
// console.log(age2) // result

// // practice arrow function
// const amount = grossrate => 500 - grossrate;
// console.log (amount(450))
// //practice aarow function
// const radhe = 70000
// const salary = divyarajsalary => radhe - divyarajsalary
// const totalsalary = radhe + 50000
// console.log(salary(50000),totalsalary)
// //practice arrow function
// const company = owner => 120000 - owner
// const ownersalary = company(100000)
// console.log(ownersalary);

// const averageofdolphins = (44 = 23 + 71)/3
// const averageofkoalas = (65 = 54 + 49)/3

//     const calcavrage = (dolphins,koalas) =>{
//     //
//     // const dolphinsavg = averageofdolphins;
//     // const koalasavg = averageofkoalas;
//     return dolphins,koalas;
// }
//    const dolphins = ((44 + 23 + 71)/3);
//    const  koalas = ((65 + 54 + 49)/3);
//     console.log(calcavrage(koalas,dolphins))
//     console.log(calcavrage(dolphins,koalas));

//     function checkwinner(avgdolphins,avgkoalas){
//         return avgdolphins,avgkoalas;

//         }
//         const dolphinboth = ((44 + 23 + 71 + 85 + 54 + 41)/6);
//         const koalasboth = ((65 + 54 + 49 + 23 + 34 + 27)/6);
//         console.log (checkwinner(dolphinboth))
// //         console.log (checkwinner(koalasboth))

// //average score
// const calcavrage = (a,b,c) => (a+b+c)/3
// console.log(calcavrage(4,5,6))

// const dolphinsavg = console.log(calcavrage(44,23,71))
// const koalasavg = console.log(calcavrage(65,54,49))
// //function of print checkwinner with the condition!
// function checkwinner(avgdolphins,avgkoalas){
//     if (avgdolphins >= 2* avgkoalas){
//     console.log(`winner is dolphines ${avgdolphins} vs ${avgkoalas}`)
//     }else if (avgkoalas >= 2* avgdolphins){
//     console.log(`winner is koalas ${avgdolphins} vs ${avgkoalas}`)
//    }else{
//     console.log(`no one wins trophy`)
//     }
// }
// checkwinner(4000,1200)

// function result(science,maths){
//     if(maths>=33&&science>=33){
//     console.log(`you are pass in both subject`)
//     }else if(science>=33){
//         console.log(`you are pass in science with ${science} number`)
//     }else if (maths>=33){
//         console.log(`you are pass in maths with ${maths} Marks`)
//     }else
//         console.log(`you are fail in both suject`)
// }
// result(322,3)

// //arrays introduction

// const laptop = ['hp','dell','apple','acer','asus'];
// console.log(laptop[3])

// const laptop1 = ['hp']; //this is type of the element metioned is array
// const laptop2 = ['dell'];
// const laptop3 = ['apple'];
// const laptop4 = ['asus'];
// const laptop5 = ['acer'];
// const totallaptop= [laptop1,laptop2,laptop3,laptop4,laptop5];//value store in one variable
// totallaptop[2] = ['desktop'] // change element in arrays apple to desktop
//  console.log(totallaptop[2]);//check the total element length and add and substract in arrays
// // uses functions with arrays
const age = (birthyear) => 1997 + birthyear;
const years = [25, 20, 29, 40];
console.log(age(years[0]));

// const netamount = (amount) => 50000- amount;

// const mobile1 = [10000]
// const mobile2 = [15000]
// const mobile3 = [20000]
// const mobiles = [mobile1,mobile2,mobile3]
// console.log(netamount(mobiles[2]))

// const calctip = (bill) => bill<=300 && bill>= 50 ? bill * .15 : bill * .20 // calculated values with arrow function

//  const value1 = (calctip(125))
//  const value2 = (calctip(555))
//  const value3 = (calctip(44))
//  console.log(value1,value2,value3)

// const bills = [125,555,44]
// console.log(calctip(bills[0]))//how to calculate tip help function for arrays
// console.log(calctip(bills[1]))
// console.log(calctip(bills[2]))

// console.log(calctip(bills[0])+ bills[0],calctip(bills[1])+ bills[1],calctip(bills[2])+ bills[2]);

// const friends = ['surbhi','manish','sachin','hemendra','kuldeep']
// console.log(friends)
// friends.push('rajveer','vishal')//add element in last in element with this methods
// console.log(friends)
// friends.unshift('pooja')//add element in start with this unshift methods
// console.log(friends)
// friends.pop()
// const myfriends = friends.pop() //show hide element value store in const variable
// console.log(friends)
// console.log(friends.includes('manish'))
// console.log(friends.indexOf('manish'))

//objects
//const cararrays = ["scorpio", "mahindra", 2022, "black", "white", "green"];

// const car = {
//   name: "scorpio",
//   company: "mahindra",
//   model: [2022, 2023],
//   colour: ["black", "white", "green"],
// };
// console.log(car["model"]);

// car.engine = `bs6`; //add element and properties again dot notation
// car["type"] = "fully automatic"; //add element and properties again bracket
// console.log(car);
// const show = prompt(
//   `what do you want about car ? name ,company, model, colour`
// );
// if (car[show]) {
//   console.log(car[show]);
// } else {
//   console.log(
//     `please choose in this properties only name ,company, model, colour `
//   );
// }

// const bestcolour = prompt(`scorpion too much sale out colour in market white , black, green , colour`)
// if(car[bestcolour]){
//     console.log(car.colour[1])
// }else{
//     console.log(`this is the not a best colour`)
// }

// const college = {
//     name : 'poonamchand gupta voacation college',
//     location : 'khandwa' ,
//     stablishment : 1990,
//     subject : ['BCOM','BSC(SEED)','BCA','DCA','BBA'],
//     teacher : 500,

// }
// console.log(college['stablishment'])

// const laptoparray =[
// 'hp',
// '5000 battery backup',
// '15 inch hd display',
// 70000,
// '8GB',
// ]
// laptoparray.pop()
// laptoparray.unshift('500gbhdd')
// console.log(laptoparray[4])

// const mobile= {
//     name : 'realme',
//     product : '3pro',
//     price : 13500,
//     year : 2016,
//     colour : [`black`,'grey','white','lightblue','darkgreen']
// }
// console.log(mobile['price'])
// const show = prompt(`type between the configarations name, product , price, year, colour`)
// console.log(mobile[show])
// if(mobile[show]){
//     console.log(mobile[show])
// }else{
//     console.log(`write the correct option`)
// }

// const person = {
//     firstname : 'sourabh',
//     lastname : 'singh',
//     height : 5.9,
//     birthyear : 1997,
//     weight : 57,
//     friends : ['rajveer', 'amjad', 'pawan', 'shubham','manish', 'akash'],
//     hasHavedrivinglicence : true,

//     calculateheight : function(){
//         return .8 + this.height
//     },

//     calculateage : function(){
//        this.age =  2022 - this.birthyear; //.this method use
//        return this.age
//     },

//     getsummary : function(){//how to work function for of function in object
//         return `my name is ${this.firstname} ${this.lastname} i am ${this.calculateage()} old and my best friend is ${this.friends['0']}  ${this.hasHavedrivinglicence ? 'yes'  : 'no' } i have driving licence this is the my height ${this.calculateheight()}`

//     },
// }
// console.log(person.friends['5'])

// // console.log(person.birthyear())// dot notation function console type
// // console.log(person['birthyear']()) //bracket notaiton console
// console.log(person.getsummary())

// const view = (prompt(`firstname,lastname,age,height,weight`))
// console.log(person[view])
//  if(person[view]){
//      console.log(`this is the value what do you want ${person[view]}`)
//  }else{
//      console.log(`please write correctly!`)
//  }

//practice of object
const companies = {
  name: "Infobeans",
  etablisment: 1997,
  employees: 500,
  revenue: 400,
  address: "crystal it park",
  owner: "sourabh",
  departments: [
    `software devloper`,
    "accountant",
    "hr manager",
    "network engineer",
    "admin",
  ],
  havedevloping: true,

  staff: function () {
    return this.employees - 100;
  },

  bestedept: function () {
    return this.departments["4"];
  },

  value: function () {
    return 100 * this.revenue;
  },

  print: function () {
    return `iam ${this.owner}  owner of ${this.name} etablish in ${
      this.etablisment
    } there is ${this.staff()} employee work here best department is ${this.bestedept()} ${
      this.havedevloping ? "yes" : "no"
    } we have licence!!`;
  },
};
console.log(companies.value());
console.log(companies.print());

//practice objects
const cricket = {
  match: 45,
  over: 20,
  indian: 220,
  pakistan: 195,
  odiance: 50000,
  commentator: ["Akash chopra", "harbhajan", "jatin sapru", "gautam gambhir"],
  umpaire: 3,
  players: ["virat", "rohit", "rahul", "bhuwneshwar", "jasprit"],
  delayduetorain: true,

  bestplayers: function () {
    return this.players[4];
  },
  delay: function () {
    return (this.delayduetorain = this.delayduetorain ? "yes" : "no");
  },
  show: function () {
    return `today held match ${this.match} indian score ${
      this.indian
    } and today matche delay due to rain ${this.delay()}`;
  },
};
console.log(cricket.show());
console.table(cricket.players);

const nm = 18;
const singh = (nm = 50) => {
  `you are great person`;
};
console.log(singh.nm);

//challenge

// const first =  {
// name : 'mark millar',
// mass : 78,
// height : 1.69,

// caclbmi : function(){
//      this.markbmi = this.mass/this.height**2
//      return this.markbmi;
// }
// }

// const second = {
//     name : 'john smith',
//     mass : 92,
//     height : 1.95,

//     caclbmi : function(){
//     this.johnbmi = this.mass/this.height**2
//     return this.johnbmi;
//     }
// }
// console.log(first.caclbmi())
// console.log(second.caclbmi());

// // if (first.caclbmi()>second.caclbmi()){
// //     console.log(`jons's BMI (${first.caclbmi()}) is higher then mark's (${second.caclbmi()}) BMI !!!`)
// // }else if (first.caclbmi()<second.caclbmi()){
// //     console.log(`mark's BMI (${first.caclbmi()}) is higher then jons's (${second.caclbmi()}) BMI !!!`)
// // }

// const laptop = {
//     name : 'hp',
//     ram : '8gb',
//     storage : 500,
//     price : 50000,
//     types : ['i3','i5','i7'],
//     speakersound : true,

//     decreament1 : function(){
//     return this.price - 5000;
//     },

//     decreament2 : function(){
//      this.newstorage = this.storage - 250
//     return this.newstorage

//     },
//     besttypes : function(){
//     return laptop.types['1']
//     }
// }
// if(laptop.speakersound){
//     console.log(`super'b hd quality sound`)
// }else{
//     console.log(`no speakers here in laptop`)
// }
// console.log(laptop.besttypes())
// // console.log(laptop.desstorage())
// console.log(laptop.decreament2())
// console.log(`we have ${laptop.name} with ${laptop.decreament2()} gb laptop buy in ${laptop.decreament1()} in new ${laptop.besttypes()} series.!!!`)

// // for loop learnings
// for(let rep = 1; rep <= 10; rep++){
//     console.log(rep)
// }

// for (let number = 50; number > 10 ; number--){
//     console.log(number)
// }

// const person= [
//     'sourabh',
//      'singh',
//       25,
//       5.9,
//       'light' ,
//       true,
//       'blackeyes'
// ]
// const type = []

// for(let i  = 0; i <person.length ; i++ ){
//     console.log(person[i])

//     // type[i] = typeof person[i];
//     // console.log(type[i])

//     type.push(typeof person[i])
//     console.log(type[i])
// }

//  const years= [
//     1997,
//     1990,
//     1974,
//     1996,
//     1945,
//     1890,
// ]
// const age = []
// const average = []

// for(i = 0; i < years.length ; i++){
//     age.push(2022 - years[i])
//     average.push(2000 - years[i])

// // }
// // console.log(age,average)

// // const bike =  [
// //     'pulsar',
// //      2013,
// //     'black&blue',
// //     'withgairs',
// //     'self',
// //     50000,
// //     ['sourabh','amjad','tosif','shubham'],
// //     true,
// // ];

// // const types =[];

// // for( i = 0; i < bike.length ; i++ ){
// //     //bike arrays properties
// //     console.log(bike[i], typeof(bike[i]))
// // //filling type arrays
// //     // types[i] = typeof bike[i];
// //     types.push(typeof bike[i]);

// // }
// // console.log(types)

// //int. in for loop

// const mobileprice = [
//     10000,
//     3523,
//     7623,
//     12342,
//     2000,
//     3245,
//     9000,
//     ['realme','iphone','micromax','intex']
// ];

// const netprice = []

// for(let i = 0; i < mobileprice.length ; i++){
//    netprice.push( 25000 - mobileprice[i]);

// }
// console.log(netprice,typeof netprice)

// //continue & break statement in loop
// console.log(`...continue with strings...`)

// for( i = 0; i < bike.length ; i++ ){
//     if(typeof bike[i] !== 'string') continue
//     console.log(bike[i],typeof bike[i])
// }
// //console.log(`...break with numbers...`)

// for( i = 0; i < bike.length ; i++ ){
//     if(typeof bike[i] === 'number') break
//     console.log(bike[i],typeof bike[i])
// }

// const mobile = [
//     10000,
//     3523,
//     7623,
//     12342,
//     2000,
//     3245,
//     9000,
//     ['realme','iphone','micromax','intex']
// ];

// //how backside print in loop
// for( i = mobile.length -1 ; i > 0; i--){
//     console.log(i,mobile[i])
// }

// //practice loop in loop
// for(mlist = 1; mlist <= 3; mlist ++){
//     console.log (`${mlist} mobile name list`)

//     for(mname = 1; mname < 6; mname++ ){
//         console.log(`${mname} realme,iphone,samsung `)
//     }

// }
// //challenges
// const invoice = [
//     22,
//     295,
//     176,
//     440,
//     37,
//     105,
//     10,
//     1100,
//     86,
//     52,
// ];
// const tips = []
// const totalvalue = []

// calctip = (invoice) => invoice<=300 && invoice>= 50 ? invoice * .15 : invoice * .20
// for(i = 0; i < invoice.length; i++ ) {

//    const tip = calctip(invoice[i])
//    //(invoice[i] <= 300 && invoice[i]>=50 ? invoice[i] * .15 : invoice[i] * .20)
//    tips.push(tip);
//    totalvalue.push(tips + invoice[i])

// }
// console.log(tips,invoice,totalvalue)

// const amount =[
//     1000,4000,3000,6000,7000,5500,
// ];

// for (i = 0; i <amount.length; i++;){
// console.log(amount)
// }

// let number = prompt(`typer your number here`);
// let items = prompt(`typer your number here`);

// for (int = 0; int <= number; int++) {
//   console.log(`master list ${int}`);
//   for (row = 0; row <= items; row++) {
//     console.log(`items of list ${row}`);
//   }
// }

// const names = ["sourabh", "manish", "rajveer", "rahul"];
// const surnames = ["rajput", "solanki", "tanwar", "sonwalkar", "verghese"];

// const namesurname = names.concat(surnames);

// console.table(names, surnames, namesurname);
// const temperature = [17, 23, 21];
// const printforecast = function (arr) {};
// temperature = [1, 4, 7, 9, 13, 17, "error", -6, -15, -9];
// const calcamplitude = function (tems) {
//   let max = tems[0];
//   for (i = 0; i < tems.length; i++) {
//     if (tems[i] > max) {
//       max = tems[i];
//     }
//   }
//   console.log(max);
// };
// calcamplitude(temperature);

for (ir = 0; ir < 10; Ir++) {
  console.log(ir);
}
for (let rep = 1; rep <= 10; rep++) {
  console.log(rep);
}
